[package]
name = "sauvignon-axum"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.8.7"
sauvignon = { path = ".." }
sqlx = { version = "0.8", features = [ "runtime-tokio", "tls-native-tls", "postgres" ] }
