[package]
name = "sauvignon"
version = "0.1.0"
edition = "2024"

[dependencies]
indexmap = "2.12.0"
thiserror = "2.0.17"
tokio = { version = "1", features = ["full"] }
sqlx = { version = "0.8", features = [ "runtime-tokio", "tls-native-tls", "postgres" ] }
anyhow = "1.0.100"
