version: '3.5'

volumes:
  local_postgres_data: {}

services:
  postgres:
    image: postgres:15
    container_name: sauvignon-postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-sauvignon}
      POSTGRES_USER: ${POSTGRES_USER:-sauvignon}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_PORT: ${POSTGRES_PORT:-5432}
      POSTGRES_HOST: ${POSTGRES_HOST:-postgres}
    volumes:
      - local_postgres_data:/var/lib/postgresql15/data
    ports:
      - "127.0.0.1:5432:5432"
