[package]
name = "sauvignon_proc_macros"
version = "0.0.1-dev.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.42"
syn = "2.0.111"
squalid = { git = "https://github.com/helixbass/squalid", rev = "1a43e5d" }
proc-macro2 = "1.0.103"
heck = "0.5.0"
